name: smartshelf
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.5
  fluttertoast: ^9.0.0
  pinput: ^5.0.0
  fl_chart: ^0.69.0
  share_plus: ^10.1.0
  csv: ^6.0.0
  path_provider: ^2.1.5
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/