// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHE9NmWkQZ4dv0U1UeZYZeM9n7WqihjWk',
    appId: '1:650324537887:web:5fb7d7f510c430fc871b2a',
    messagingSenderId: '650324537887',
    projectId: 'smartshelf-03',
    authDomain: 'smartshelf-03.firebaseapp.com',
    storageBucket: 'smartshelf-03.firebasestorage.app',
    measurementId: 'G-HPF3HDX4S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo2bq4M7HHYHzXcyPQ4XAj1y2JSYlrsDk',
    appId: '1:650324537887:android:0eb13d85dc2ce756871b2a',
    messagingSenderId: '650324537887',
    projectId: 'smartshelf-03',
    storageBucket: 'smartshelf-03.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtFDFAwbNFn3tsSV3BqT_lih7GWromsrE',
    appId: '1:650324537887:ios:8ef9987b0dbbc9dd871b2a',
    messagingSenderId: '650324537887',
    projectId: 'smartshelf-03',
    storageBucket: 'smartshelf-03.firebasestorage.app',
    iosBundleId: 'com.smartshelf.smartshelf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHE9NmWkQZ4dv0U1UeZYZeM9n7WqihjWk',
    appId: '1:650324537887:web:7160b19a46180660871b2a',
    messagingSenderId: '650324537887',
    projectId: 'smartshelf-03',
    authDomain: 'smartshelf-03.firebaseapp.com',
    storageBucket: 'smartshelf-03.firebasestorage.app',
    measurementId: 'G-RZ19QVQQKL',
  );
}
